### ISSUE TITLE
Sample code for buttons not working

### ISSUE THREAD

**Issue by dippyhippy** [ameltech/sme-arduino-core#13]
I am attempting to get some of the example code running, firstly had to "touch ~/.android15/AMEL/hardware/samd/1.0.0/libraries/SME_basic/SME_basic.h" to get the examples to show up and then:

userButton: red and blue leds stay on constantly
IsOnBattery: reports it's running on battery when it's on a mains charger

Is this a problem with your code or my board?

**Comment by dippyhippy** [comment]
Not a problem with my board. Adding pinMode(41, INPUT_PULLUP) to setup() gets it working.

**Comment by smkkHw** [comment]
Hi Dippyhippy.

It should not be necessary as per line 97 on
hardware/AMEL/samd/variants/AMEL_SmartEverything/variantInit.cpp

**Comment by dippyhippy** [comment]
Hi,

I'm well aware it shouldn't be necessary...but it is!

regards,

Ben

**Comment by smkkHw** [comment]
Interesting, because I use the button often for other sketch and never had the needed to add  a second time the definition of the pin.

Could U please remove your second definition  and try the following?

1) press a little bit longer the button 1
2) perfrom the same test on button 2 (maybe it is only on 1)

**Comment by dippyhippy** [comment]
That makes no difference. I haven't included the code for button 2, but
it's neccessary to also do the pinMode to get that working too.

**Comment by smkkHw** [comment]
I tried on different HW without problem.

If soneone else experience the same problem could re-open the issue

**Comment by dippyhippy** [comment]
Did you try it on my hardware? I'm sorry but I find your response insulting. Do you not think me capable of following a set of three instructions to produce an output? Perhaps ask me to do some rudimentary debugging so I can demonstrate to you that my device isn't doing the same as yours. Or how about checking what version of the Arduino IDE I am using, or what versions of the modules etc. Or alternatively just close the ticket!!

Why is someone else going to even see the issue when you've closed it?

**Comment by smkkHw** [comment]
Do not insulting anyone.

just saying that I tried on several Hw and works as expected.

What I did with the close of the Issue is that is not a SW Issue , absolutely my intention is not to offend anyone.
Maybe Hw timing? do not known if I do not have your Hw to test on.

In fact I also wrote .... 
"if someone else experience the same problem could re-open the issue".

Just this, nothing more, sorry again if this apology could help to calm down the level.
